gpu_id: 0
load_meshhead_checkpoint: 'checkpoints/meshhead_renderme/meshhead_latest'
# load_gaussianhead_checkpoint: 'checkpoints/gaussianhead_renderme/gaussianhead_latest'
# load_gaussianhead_checkpoint: 'checkpoints/gaussianhead_renderme/gaussianhead_latest'
load_supres_checkpoint: 'checkpoints/gaussianhead_renderme/supres_latest'
load_delta_poses_checkpoint: 'checkpoints/gaussianhead_renderme/delta_poses_latest'
lr_net: 1e-4
lr_pose: 1e-5
batch_size: 1
optimize_pose: True
use_supres: True 
train_segment: True
train_optical_flow: False 
checkpoint_seed: 175029050023 
resume_training: False
start_epoch: 0
num_epochs: 18000 # 1800 # 400   

dataset:
  dataroot: ''
  camera_ids: []
  test_camera_ids: [0, 25]
  selected_frames: []
  # selected_frames: ['0000']
  original_resolution: 2048
  resolution: 2048
  # coarse_scale_factor: 1.0  

loss_weights:
  dir: 10.
  dssim: 0.2
  knn_feature: 10.
  mesh_dist: 0.001
  orient: 1.
  rgb_hr: 1.
  rgb_lr: 1.
  segment: 2.
  sign_distance: 0.01
  strand_feature: 0.01
  transform_reg: 10.
  vgg: 0.1

meshheadmodule:
  geo_mlp: [27, 256, 256, 256, 256, 256, 132]
  exp_color_mlp: [192, 256, 256, 32]
  pose_color_mlp: [182, 128, 32]
  exp_deform_mlp: [91, 256, 256, 256, 256, 256, 3]
  pose_deform_mlp: [81, 256, 256, 3]
  pos_freq: 4
  model_bbox: [[-1.6, 1.6], [-1.7, 1.8], [-2.5, 1.0]]
  dist_threshold_near: 0.1
  dist_threshold_far: 0.25
  deform_scale: 0.3
  subdivide: False

supresmodule:
  input_dim: 32
  output_dim: 3
  network_capacity: 4

gaussianheadmodule:
  enable: True
  num_add_mouth_points: 3000
  exp_color_mlp: [192, 256, 256, 32]
  pose_color_mlp: [182, 128, 32]
  exp_deform_mlp: [91, 256, 256, 256,256,256, 3]
  pose_deform_mlp: [81, 256, 256, 3]
  exp_attributes_mlp: [192, 256, 256, 256, 8]
  pose_attributes_mlp: [182, 128, 128, 8]
  exp_coeffs_dim: 64
  pos_freq: 4
  dist_threshold_near: 0.1
  dist_threshold_far: 0.25
  deform_scale: 0.3
  attributes_scale: 0.2

  densify: False
  densification_interval: 100
  opacity_reset_interval: 3_000
  densify_from_iter: 500
  densify_until_iter: 15_000
  # densify_grad_threshold: 0.0002
  densify_grad_threshold: 0.0004
  opacity_reg_from_iter: 30_000
  gaussian_pruning_threshold: 0.5

gaussianhairmodule:
  enable: False

flame_gaussian_module:
  enable: False
  

recorder:
  debug_tool: 'wandb' # 'tensorboard' or 'wandb'
  name: 'gaussianhead_renderme'
  logdir: 'log/gaussianhead_NeRSemble031_Simplified'
  checkpoint_path: 'checkpoints'
  result_path: 'results'
  save_freq: 10000
  show_freq: 500
